title: Nova Roleplay APV
description:  Nova Roleplay APV 
                icon = "https://media.discordapp.net/attachments/1431917700988538900/1444720458753638602/d20cdb14-ed85-4dc3-9fc1-a21bc58ba422.png?ex=692f0dc6&is=692dbc46&hm=3dadeda1f22faae0396c459f0a4e1660ddafc1178998d861a7d37139f1afbc29&=&format=webp&quality=lossless",
                
# Development server config, needed to load some of the content
webrick:
  headers:
    Access-Control-Allow-Origin: "*"

# Theme settings
site_author: Carlos Pereira Atencio
repo_url: 'https://github.com/carlosperate/jekyll-theme-rtd'
edit_on_github: true
github_docs_folder: false
sticky_navigation: true
prev_next_buttons_location: both
search_enabled: true
hljs_style: github-gist
